### ISSUE TITLE
Error: reading ZIP file while deploying AFT 

### ISSUE THREAD

**Issue by lironsi** [aws-ia/terraform-aws-control_tower_account_factory#475]
Hello,
I'm trying to deploy AFT in my organization and get the following error -

```
 │ Error: reading ZIP file (.terraform/modules/aft/modules/aft-archives/../../src/aft_lambda/aft_builder.zip): open .terraform/modules/aft/modules/aft-archives/../../src/aft_lambda/aft_builder.zip: no such file or directory
│ 
│   with module.aft.module.aft_lambda_layer.aws_lambda_function.codebuild_trigger,
│   on .terraform/modules/aft/modules/aft-lambda-layer/lambda.tf line 6, in resource "aws_lambda_function" "codebuild_trigger":
│    6: resource "aws_lambda_function" "codebuild_trigger" {
```
the module source I set is "github.com/aws-ia/terraform-aws-control_tower_account_factory"

Please advise, this is a real blocker..
Thanks
Liron

**Comment by cyrildmoses** [comment]
Hi @lironsi,

I encountered the same error while deploying AFT through CodePipeline. Have you found a solution for this issue?

Thanks!

**Comment by robinbihun** [comment]
Hey all, the zips are created in the `terraform plan` stage so if you are running plan and apply in separate ci/cd stages and running `terraform apply {plan-file}` then you also need to be sure to pass the zips from the plan artifacts to the apply stage.

For example, if you are using gitlab pipelines something like the following should work for you:
```
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/.terraform/modules/aft/src/aft_lambda/*.zip"
    expire_in: 1 day
```

**Comment by cjrowe** [comment]
Further to the comment above from @robinbihun can confirm we had the same issue running separate GitHub Actions Workflow jobs for `terraform plan` and `terraform apply`. In the absence of a fix, the workaround we used was to cache the Terraform directory by adding the following step to each job:

```yaml
- name: Configure Cache for Terraform Modules
   uses: actions/cache@v4
   with:
     path: .terraform
     key: terraform-modules-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
     restore-keys: |
       terraform-modules-${{ runner.os }}-
```
